routes/web.php
<?php

use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\Auth\RegisterController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\StudentsController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/register', RegisterController::class . '@index')->name('register.show');
Route::post('/register', RegisterController::class . '@create')->name('register');

Route::get('/login', LoginController::class . '@index')->name('login.show');
Route::post('/login', LoginController::class . '@login')->name('login');
Route::post('/logout', LoginController::class . '@logout')->name('logout');

Route::group(['middleware' => ['web', 'auth']], function () {
    Route::get('/home', HomeController::class . '@index')->name('home');

    Route::resource('students', StudentsController::class);
});

app/Models/Employee.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Employee extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'age',
        'salary',
        'profile_picture'
    ];
}

app/Models/Student.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Student extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'first_name',
        'last_name',
        'address',
    ];

    public function getFullNameAttribute()
    {
        $arr = [$this->first_name, $this->last_name];
        return implode(' ', $arr);
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    const ROLE_ADMIN = 1;
    const ROLE_MANAGER = 2;

    const IMAGES_FOLDER = 'images/users';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'age',
        'dob',
        'address',
        'password',
        'role',
        'profile_picture',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password'
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [];

    /**
     * Get role text.
     *
     * @return array|mixed|null|string
     */
    public function getRoleTextAttribute()
    {
        return self::getRoles()[$this->role] ?? __('Unknown');
    }

    /**
     * Get available roles.
     *
     * @return array
     */
    public static function getRoles()
    {
        return [
            self::ROLE_ADMIN => __('Admin'),
            self::ROLE_MANAGER => __('Manager'),
        ];
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Auth;

class HomeController extends Controller
{
    /**
     * Show home page to logged in users.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
     */
    public function index()
    {
        $user = Auth::user();

        return view('home', compact('user'));
    }
}

app/Http/Controllers/StudentsController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StudentRequest;
use App\Models\Student;
use Illuminate\Http\Request;

class StudentsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $students = Student::paginate(10);

        return view('students.index', compact('students'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $student = new Student;

        return view('students.create', compact('student'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  StudentRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StudentRequest $request)
    {
        $student = Student::create($request->validated());
        return redirect()->route('students.show', $student);
    }

    /**
     * Display the specified resource.
     *
     * @param  Student $student
     * @return \Illuminate\Http\Response
     */
    public function show(Student $student)
    {
        return view('students.show', compact('student'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  Student $student
     * @return \Illuminate\Http\Response
     */
    public function edit(Student $student)
    {
        return view('students.edit', compact('student'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  StudentRequest  $request
     * @param  Student $student
     * @return \Illuminate\Http\Response
     */
    public function update(StudentRequest $request, Student $student)
    {
        $student->update($request->validated());
        return redirect()->route('students.show', $student);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  Student $student
     * @return \Illuminate\Http\Response
     */
    public function destroy(Student $student)
    {
        $student->delete();
        return redirect()->route('students.index', $student);
    }
}

resources/views/home.blade.php
@extends("layouts.main")

@section('title', __('Home page'))

@section("content")
    @if(session()->has('success'))
        <span class="text-center d-block alert alert-success">
            <strong>{{ session()->get('success') }}</strong>
        </span>
        <br/> <br/>
    @endif
    <p class="text-center">{{ __('Welcome') . ' ' . $user->name }}</p>
    <img src="{{asset('/storage/' . App\Models\User::IMAGES_FOLDER . '/' . $user->profile_picture)}}"
         class="d-block col-md-2 m-auto" alt="{{ $user->name . ' ' . __('image') }}" />
    <p class="text-center">{{ __('You\'re ') . ' ' . $user->role_text }}</p>
    @php
        use \App\Models\User;
        if ($user->role == User::ROLE_ADMIN) {
            $welcomeText = __('You can do anything');
        } elseif ($user->role == User::ROLE_MANAGER) {
            $welcomeText = __('You can manage some things');
        }
    @endphp
    <p class="text-center">{{ $welcomeText }}</p>
@endsection

resources/views/layouts/main.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>{{ config('app.name') }} - @yield('title')</title>

        <link href="{{ asset('css/app.css') }}" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.5.0/css/bootstrap-datepicker.css">

        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    </head>
    <body class="antialiased">
        <div class="relative items-top justify-center min-h-screen bg-gray-100 dark:bg-gray-900 sm:items-center py-4 sm:pt-0">
            <div class="hidden fixed top-0 right-0 px-6 py-4 sm:block">
                @auth
                    <a href="{{ url('/home') }}" class="text-sm text-gray-700 underline">Home</a>
                    <a href="{{ route('logout') }}" class="text-sm text-gray-700 underline"
                       onclick="event.preventDefault();
                                    document.getElementById('logout-form').submit();">
                        {{ __('Logout') }}
                    </a>
                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                        @csrf
                    </form>
                @else
                    <a href="{{ route('login.show') }}" class="text-sm text-gray-700 underline">Log in</a>
                    <a href="{{ route('register.show') }}" class="ml-4 text-sm text-gray-700 underline">Register</a>
                @endauth
            </div>
            @yield('content')
        </div>
        @yield('additionalScripts')
    </body>
</html>

resources/views/students/create.blade.php
@extends("layouts.main")

@section('title', __('Create student'))

@section("content")
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header"><h4>{{ __('Create student') }}</h4></div>
                    <div class="card-body">
                        <form method="POST" action="{{ route('students.store') }}">
                            @csrf
                            @include('students.partials.create-edit')
                            <div class="form-group row mb-0">
                                <div class="col-md-6 offset-md-4">
                                    <button type="submit" class="btn btn-primary">
                                        {{ __('Create') }}
                                    </button>
                                    <a href="{{ route('students.index') }}">{{ __('Cancel') }}</a>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/students/edit.blade.php
@extends("layouts.main")

@section('title', __('Edit student') . ' ' . $student->full_name)

@section("content")
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header"><h4>{{ __('Edit student') . ' ' . $student->full_name }}</h4></div>
                    <div class="card-body">
                        <form method="POST" action="{{ route('students.update', $student) }}">
                            @csrf
                            @method('put')
                            @include('students.partials.create-edit')
                            <div class="form-group row mb-0">
                                <div class="col-md-6 offset-md-4">
                                    <button type="submit" class="btn btn-primary">
                                        {{ __('Save') }}
                                    </button>
                                    <a href="{{ route('students.show', $student) }}">{{ __('Cancel') }}</a>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/students/index.blade.php
@extends("layouts.main")

@section('title', __('All students'))

@section("content")
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <a href="{{ route('students.create') }}">{{ __('Create') }}</a>
                    <table>
                        <thead>
                        <tr>
                            <th>{{ __('Firtname') }}</th>
                            <th>{{ __('Lastname') }}</th>
                            <th>{{ __('Address') }}</th>
                            <th>{{ __('Actions') }}</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach ($students as $student)
                            <tr>
                                <td>{{ $student->first_name }}</td>
                                <td>{{ $student->last_name }}</td>
                                <td>{{ $student->address }}</td>
                                <td>
                                    <a href="{{ route('students.show', $student) }}">{{ __('Show') }}</a>
                                    <a href="{{ route('students.edit', $student) }}">{{ __('Edit') }}</a>

                                    <a href="{{ route('students.destroy', $student) }}"
                                       onclick="event.preventDefault();
                                                document.getElementById('delete-form-{{ $student->id }}').submit();">
                                        {{ __('Delete') }}
                                    </a>
                                    <form id="delete-form-{{ $student->id }}" action="{{ route('students.destroy', $student) }}" method="POST" class="d-none">
                                        @csrf
                                        @method('delete')
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                    {{ $students->links() }}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/students/partials/create-edit.blade.php
<div class="form-group row">
    <label for="first_name" class="col-md-4 col-form-label text-md-right">{{ __('Firstname') }}</label>
    <div class="col-md-6">
        <input id="first_name" type="text" class="form-control @error('first_name') is-invalid @enderror"
               name="first_name" value="{{ old('first_name', $student->first_name) }}" required autocomplete="first_name" autofocus>
        @error('first_name')
        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
        @enderror
    </div>
</div>
<div class="form-group row">
    <label for="last_name" class="col-md-4 col-form-label text-md-right">{{ __('Lastname') }}</label>
    <div class="col-md-6">
        <input id="last_name" type="text" class="form-control @error('last_name') is-invalid @enderror"
               name="last_name" value="{{ old('last_name', $student->last_name) }}" autocomplete="last_name" autofocus>
        @error('last_name')
        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
        @enderror
    </div>
</div>
<div class="form-group row">
    <label for="address" class="col-md-4 col-form-label text-md-right">{{ __('Address') }}</label>
    <div class="col-md-6">
        <input type="text" id="address" class="form-control @error('address') is-invalid @enderror"
               name="address" value="{{ old('address', $student->address) }}" required autocomplete="address">
        @error('address')
        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
        @enderror
    </div>
</div>

resources/views/students/show.blade.php
@extends("layouts.main")

@section('title', __('Show student') . ' ' . $student->full_name)

@section("content")
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header"><h4>{{ __('Show student') . ' ' . $student->full_name }}</h4></div>
                    <div class="card-body">
                        <p>{{ __('Firstname') . ': ' . $student->first_name }}</p>
                        <p>{{ __('Lastname') . ': ' . $student->last_name }}</p>
                        <p>{{ __('Address') . ': ' . $student->address }}</p>
                    </div>
                </div>
                <a href="{{ route('students.edit', $student) }}">{{ __('Edit') }}</a>
                <a href="{{ route('students.destroy', $student) }}"
                   onclick="event.preventDefault();
                           document.getElementById('delete-form-{{ $student->id }}').submit();">
                    {{ __('Delete') }}
                </a>
                <form id="delete-form-{{ $student->id }}" action="{{ route('students.destroy', $student) }}" method="POST" class="d-none">
                    @csrf
                    @method('delete')
                </form>
                <a href="{{ route('students.index') }}">{{ __('All Students') }}</a>
            </div>
        </div>
    </div>
@endsection